// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// A class that exposes all available Firebase options.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.macOS)) {
      return macos;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.fuchsia)) {
      return web;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.windows)) {
      return windows;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.linux)) {
      return linux;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4pg4GE0f4y9ShbIUFSgoAdiMbJgbY0Z0',
    appId: '1:81090432768:android:8f533e8d35ba0cc0912de5',
    messagingSenderId: '81090432768',
    projectId: 'flexihire-78d74',
    storageBucket: 'flexihire-78d74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj_hL00XvjYF50OsNP2T91foAfZ1W5uYU',
    appId: '1:81090432768:ios:f2a850006c2d9963912de5',
    messagingSenderId: '81090432768',
    projectId: 'flexihire-78d74',
    storageBucket: 'flexihire-78d74.firebasestorage.app',
    iosBundleId: 'com.example.module4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj_hL00XvjYF50OsNP2T91foAfZ1W5uYU',
    appId: '1:81090432768:ios:f2a850006c2d9963912de5',
    messagingSenderId: '81090432768',
    projectId: 'flexihire-78d74',
    storageBucket: 'flexihire-78d74.firebasestorage.app',
    iosBundleId: 'com.example.module4',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSJoqSnZmRrh2Wq0dTc5SNC_XCV8eKEXo',
    appId: '1:81090432768:web:6303f34fcde188d8912de5',
    messagingSenderId: '81090432768',
    projectId: 'flexihire-78d74',
    authDomain: 'flexihire-78d74.firebaseapp.com',
    storageBucket: 'flexihire-78d74.firebasestorage.app',
    measurementId: 'G-W7Y4Y64XJ3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSJoqSnZmRrh2Wq0dTc5SNC_XCV8eKEXo',
    appId: '1:81090432768:web:8bfb81f0fefd7a5c912de5',
    messagingSenderId: '81090432768',
    projectId: 'flexihire-78d74',
    authDomain: 'flexihire-78d74.firebaseapp.com',
    storageBucket: 'flexihire-78d74.firebasestorage.app',
    measurementId: 'G-22KE0C0Y23',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyD4pg4GE0f4y9ShbIUFSgoAdiMbJgbY0Z0',
    appId: '1:81090432768:linux:your_linux_app_id',
    messagingSenderId: '81090432768',
    projectId: 'flexihire-78d74',
    storageBucket: 'flexihire-78d74.firebasestorage.app',
    authDomain: 'flexihire-78d74.firebaseapp.com',
  );
}

